version: '3.7'

services:
  postgres:
    container_name: postgres-local
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - local-stack
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-local
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - local-stack
    restart: unless-stopped
  redis:
    container_name: redis-local
    image: redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    networks:
      - local-stack
    restart: unless-stopped
  mongo:
    container_name: mongo-local
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - local-stack
    volumes:
      - mongo:/data/db
    restart: unless-stopped

networks:
  local-stack:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis:
  mongo:
